### ISSUE TITLE
How to use this ?

### ISSUE THREAD

**Issue by afoysal** [filipelinhares/vuejs-snippets-sublime#13]
How to use this ?

**Comment by filipelinhares** [comment]
Hi @afoysal.

First you need to install it using [Package Control](https://packagecontrol.io/).

To use just type one of the [snippets](https://github.com/filipelinhares/vuejs-snippets-sublime#snippets), hit tab and it will autocomplete to you, e.g:

1. Type `v-for`
2. Hit <kbd>tab ⇥</kbd>
3. It will expand to:
```
<div v-for="item in items">
</div>
```
