### ISSUE TITLE
Strange snippet for vueprops

### ISSUE THREAD

**Issue by Pintiboy** [filipelinhares/vuejs-snippets-sublime#14]
The snippet, i.e. rather the placeholders for "vuecprops", behaves a bit strange. After entering "vuecprops -> tab" Sublime wants you to give it a Name AND the type simultaneously. Why should the name be the same as the type?

**Comment by filipelinhares** [comment]
Thanks for your report @Pintiboy. It is an unexpected behavior, I'm fixing it.
